language: python
dist: xenial

# do not run Travis for PR's twice (as for push and as for PR)
branches:
  only:
    - master

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  # - curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.6/bin/python
  # https://github.com/travis-ci/travis-ci/issues/8589
  - >
    /opt/python/3.7/bin/python install.py
    --branch=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    --slug=${TRAVIS_PULL_REQUEST_SLUG:-dephell/dephell}
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python" --level=DEBUG --traceback
  - dephell deps install --env=$ENV --level=DEBUG --traceback
script:
  - dephell venv run --env=$ENV --level=DEBUG --traceback

matrix:
  include:
    - python: "3.6.7"
      env: ENV=pytest
    - python: "3.7"
      env: ENV=pytest
    - python: "3.8"
      env: ENV=pytest
    - python: "pypy3"
      env: ENV=pytest

    - os: osx
      language: generic
      env: ENV=pytest
      before_install:
        - >
          /usr/local/bin/python3 install.py
          --branch=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
          --slug=${TRAVIS_PULL_REQUEST_SLUG:-dephell/dephell}
        - dephell inspect self
      install:
        - dephell venv create --env=$ENV --python=/usr/local/bin/python3 --level=DEBUG --traceback
        - dephell deps install --env=$ENV --level=DEBUG --traceback

    # https://github.com/igorshubovych/markdownlint-cli
    - name: markdown lint
      language: node_js
      node_js: "14"
      before_install:
        - true
      install:
        - npm install -g markdownlint-cli
      script:
        - bash -c "markdownlint --config markdownlint.json **/*.md"

    - name: offline
      python: "3.7"
      env: ENV=pytest
      script:
        - dephell venv run --env=$ENV pytest --no-network tests/

    - python: "3.7"
      env: ENV=flake8

    - python: "3.7"
      env: ENV=typing

    - python: "3.7"
      env: ENV=isort
      script:
        - dephell venv run --env=$ENV flake8

    - python: "3.7"
      env: ENV=docs

    - name: poetry
      python: "3.7"
      env: ENV=main
      before_install:
        - pip install poetry
      install:
        - poetry install -vvv
      script:
        - dephell inspect self
